# Generated by Django 3.1.4 on 2021-10-16 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='link_token',
            field=models.CharField(blank=True, default='', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player', unique=True)),
            ],
        ),
    ]
