# Generated by Django 3.1.4 on 2021-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211016_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='link_token',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
