# Generated by Django 3.1.4 on 2021-10-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211018_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='uid',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
