# Generated by Django 3.1.4 on 2021-11-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211102_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mode',
        ),
        migrations.AddField(
            model_name='player',
            name='bot',
            field=models.BooleanField(default=False),
        ),
    ]
