# Generated by Django 3.1.4 on 2021-11-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211109_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.PositiveIntegerField(default=400),
        ),
    ]
